# Site settings
title: Agnes Garcia
description: Agnes Garcia
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Agnes Garcia
user_description: Thanks for visiting! I'm Agnes and I am an aspiring software engineer currently studying Computer Science and minoring in Psychology at UC San Diego. When I'm not busy coding, I love planning outreach events for girls in STEM, traveling, and trying out new restaurants. Feel free to scroll through to learn more about me!
user_title: Software Engineer
email: agnesgar@icloud.com
#twitter_username: lorem_ipsum
github_username:  agnesg4
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
